language: php

sudo: false

matrix:
  fast_finish: true
  include:
  - php: 7.2
    env:
      - TYPO3_VERSION=^9
      - SNIFF=1

before_script:
- if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
- travis_wait composer require typo3/minimal=$TYPO3_VERSION -vvv
- export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
- |
  if [[ "$SNIFF" == "1" ]]; then echo; echo "Running PHP Coding Standards Fixer checks"; .Build/bin/php-cs-fixer fix --config=.Build/.php_cs -v --dry-run --using-cache=no; fi
- |
  echo; echo "Running Unittests"; .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml ./Tests/Unit/
