language: php

sudo: false

matrix:
  fast_finish: true
  include:
  include:
    - php: 7.2
      env: TYPO3_VERSION=^9 TESTING_FRAMEWORK=^4 FUNCTIONALS=1 COVERAGE=0
    - php: 7.3
      env: TYPO3_VERSION=^9 TESTING_FRAMEWORK=^4 FUNCTIONALS=1 COVERAGE=0
    - php: 7.4
      env: TYPO3_VERSION=^9 TESTING_FRAMEWORK=^4 FUNCTIONALS=1 COVERAGE=0
    - php: 7.2
      env: TYPO3_VERSION=^10 TESTING_FRAMEWORK=^5 FUNCTIONALS=1 COVERAGE=0
    - php: 7.3
      env: TYPO3_VERSION=^10 TESTING_FRAMEWORK=^5 FUNCTIONALS=1 COVERAGE=0
    - php: 7.4
      env: TYPO3_VERSION=^10 TESTING_FRAMEWORK=^5 FUNCTIONALS=1 COVERAGE=0

before_script:
- if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
- travis_wait composer require typo3/minimal=$TYPO3_VERSION -vvv
- export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
- |
  if [[ "$SNIFF" == "1" ]]; then echo; echo "Running PHP Coding Standards Fixer checks"; .Build/bin/php-cs-fixer fix --config=.Build/.php_cs -v --dry-run --using-cache=no; fi
