services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Oktopuce\SiteGenerator\:
    resource: '../Classes/*'

  Oktopuce\SiteGenerator\Wizard\StateCreateFolder:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Wizard\StateCreateGroupHomeFolder:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Hook\BackendControllerHook:
    public: true
    shared: false
