services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Oktopuce\SiteGenerator\:
    resource: '../Classes/*'

  Oktopuce\SiteGenerator\Wizard\StateCreateFolder:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Wizard\StateUpdateTemplateHP:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Wizard\StateSiteConfiguration:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Wizard\StateCopyModelSite:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Wizard\StateUpdatePageTs:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Wizard\StateCreateFileMount:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Wizard\StateCreateFeGroup:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Wizard\StateCreateBeGroup:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Wizard\StateUpdateHomePage:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Wizard\StateSetPageBeGroup:
    public: true
    shared: false

  Oktopuce\SiteGenerator\Controller\SiteGeneratorController:
    public: true
    shared: false
